import '../styles/globals.css';
import 'antd/dist/antd.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { ComponentTable } from '../components';
import styles from '../styles/Home.module.css';
import { Button, PageHeader, Row, message } from 'antd';
import { useRouter } from 'next/router';
import useStore from '../utils/store';

function MyApp({ Component, pageProps }: AppProps) {
  const fetchData = useStore((state) => state.fetchData),
    loggedUser = useStore((state) => state.loggedUser),
    setUser = useStore((state) => state.setUser),
    [dataModal, setDataModal] = useState(false),
    router = useRouter(),
    useLogin = () => {
      if (loggedUser) {
        return [
          <span key='1'>Halo {loggedUser}</span>,
          <Button
            key='2'
            onClick={() => {
              setUser(null);
              localStorage.removeItem('token');
              message.success('You have been logged out');
            }}
          >
            Log out
          </Button>,
        ];
      } else {
        return [
          <Button key='1' onClick={() => router.push('/register')}>
            Register
          </Button>,
          <Button key='2' onClick={() => router.push('/login')}>
            Login
          </Button>,
        ];
      }
    };

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Tabel Data Obat</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.navbar}>DATA STOK OBAT</h1>
        <PageHeader
          title='TABEL DATA OBAT'
          className={styles.content}
          extra={useLogin()}
        >
          <Row>
            <ComponentTable setToggle={setDataModal} />
          </Row>
        </PageHeader>
      </main>
      <Component {...pageProps} />

      <footer className={styles.footer}>
        <span>Wicaksana Pratama @ 2022</span>
      </footer>
    </div>
  );
}

export default MyApp;
