import '../styles/globals.css';
import 'antd/dist/antd.css';
import type { AppProps } from 'next/app';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { ComponentTable, DataModal } from '../components';
import styles from '../styles/Home.module.css';
import { Button, PageHeader, Row, message } from 'antd';
import { ItemsWithKey } from '../utils/types';
import { useRouter } from 'next/router';
import useStore from '../utils/store';

function MyApp({ Component, pageProps }: AppProps) {
  const fetchData = useStore((state) => state.fetchData),
    loggedUser = useStore((state) => state.loggedUser),
    setUser = useStore((state) => state.setUser),
    [dataModal, setDataModal] = useState(false),
    router = useRouter(),
    useLogin = () => {
      if (loggedUser) {
        return [
          <span key='1'>Halo Kamu</span>,
          <Button
            key='2'
            onClick={() => {
              setUser(null);
              localStorage.removeItem('token');
              message.success('You have been logged out');
            }}
          >
            Log out
          </Button>,
        ];
      } else {
        return [
          <Button key='1' onClick={() => router.push('/register')}>
            Register
          </Button>,
          <Button key='2' onClick={() => router.push('/login')}>
            Login
          </Button>,
        ];
      }
    };

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <PageHeader
          title='TABEL DATA OBAT'
          className={styles.content}
          extra={useLogin()}
        >
          <Row>
            <ComponentTable setToggle={setDataModal} />
          </Row>
        </PageHeader>
      </main>
      {/* <DataModal toggle={dataModal} setToggle={toggleDataModal} /> */}
      <Component {...pageProps} />

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export default MyApp;
