import type { NextPage } from 'next';
// import Head from 'next/head';
// import Image from 'next/image';
// import { useEffect, useState } from 'react';
// import { ComponentTable, DataModal } from '../components';
// import styles from '../styles/Home.module.css';
// import { Button, PageHeader, Row } from 'antd';
// import { ItemsWithKey } from '../utils/types';

// const Home: NextPage = () => {
//   const [data, setData] = useState<ItemsWithKey[] | null>(null),
//     [dataModal, setDataModal] = useState(false),
//     fetchData = async () => {
//       const res = await fetch('/api/items'),
//         parsed = await res.json();
//       setData(parsed);
//     };

//   useEffect(() => {
//     fetchData();
//   }, []);
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name='description' content='Generated by create next app' />
//         <link rel='icon' href='/favicon.ico' />
//       </Head>

//       <main className={styles.main}>
//         <PageHeader
//           // title='TABEL DATA OBAT'
//           className={styles.content}
//           extra={[
//             <Button key='1' onClick={() => setDataModal(true)}>
//               Register
//             </Button>,
//             <Button key='2'>Login</Button>,
//           ]}
//         >
//           <Row>
//             <ComponentTable data={data} setToggle={setDataModal} />
//           </Row>
//         </PageHeader>
//       </main>
//       <DataModal toggle={dataModal} setToggle={setDataModal} />

//       <footer className={styles.footer}>
//         <a
//           href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
//           target='_blank'
//           rel='noopener noreferrer'
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   );
// };

const Home: NextPage = () => {
  return (
    <div>
      <span></span>
    </div>
  );
};
export default Home;
